import Config

database_url = System.get_env("DATABASE_URL")

repo_config =
  if database_url do
    # Use the DATABASE_URL hostname directly — Postgrex parses it and
    # socket_options: [:inet6] tells Erlang to do an IPv6 (AAAA) DNS lookup
    # and connect over IPv6 to Supabase's direct connection endpoint.
    [
      url: database_url,
      socket_options: [:inet6]
    ]
  else
    [
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "nxtvibes_dev"
    ]
  end

config :nxtvibes, NxtVibes.Repo,
  repo_config ++
    [
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 20
    ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nxtvibes, NxtVibesWeb.Endpoint,
  # Change to {0, 0, 0, 0} to allow access from Android emulator (10.0.2.2) and other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NyTXOlNWZnthyDjOecX8lUHCY7YrcY+uwIZtXKq6IIbB/aHW5KiqFe49HIxVOtGU",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :nxtvibes, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
