const path = require('path');
const fs = require('fs');
const { withDangerousMod } = require('@expo/config-plugins');

const googleMapsApiKey = process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY || '';
const notifeeLibsPath = path.resolve(__dirname, 'node_modules/@notifee/react-native/android/libs').replace(/\\/g, '/');

function copyFolderRecursiveSync(source, target) {
  if (!fs.existsSync(source)) return;
  if (!fs.existsSync(target)) {
    fs.mkdirSync(target, { recursive: true });
  }

  const files = fs.readdirSync(source);
  for (const file of files) {
    const curSource = path.join(source, file);
    const curTarget = path.join(target, file);
    if (fs.lstatSync(curSource).isDirectory()) {
      copyFolderRecursiveSync(curSource, curTarget);
    } else {
      fs.copyFileSync(curSource, curTarget);
    }
  }
}

const withCustomAndroidIcons = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const sourceDir = path.join(config.modRequest.projectRoot, 'assets/res');
      const targetDir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res');
      
      if (fs.existsSync(sourceDir)) {
        console.log('[withCustomAndroidIcons] Copying custom launcher icons...');
        
        // Delete conflicting .webp files generated by Expo
        if (fs.existsSync(targetDir)) {
          const folders = fs.readdirSync(targetDir);
          for (const folder of folders) {
            if (folder.startsWith('mipmap-')) {
              const folderPath = path.join(targetDir, folder);
              if (fs.lstatSync(folderPath).isDirectory()) {
                const files = fs.readdirSync(folderPath);
                for (const file of files) {
                  if (file.startsWith('ic_launcher') && file.endsWith('.webp')) {
                    fs.unlinkSync(path.join(folderPath, file));
                  }
                }
              }
            }
          }
        }

        copyFolderRecursiveSync(sourceDir, targetDir);
      }
      return config;
    },
  ]);
};

module.exports = {
  expo: {
    name: 'NxtVibes',
    slug: 'mobile',
    version: '1.0.0',
    scheme: 'nxtvibes',
    orientation: 'portrait',
    icon: './assets/applogo.png',
    userInterfaceStyle: 'automatic',
    backgroundColor: '#0F0F0F',
    splash: {
      image: './assets/applogo.png',
      resizeMode: 'contain',
      backgroundColor: '#9d74f7',
    },
    extra: {
      eas: {
        projectId: '3070be5b-0bdf-464b-b994-81505f567054',
      },
    },
    ios: {
      supportsTablet: true,
      bundleIdentifier: 'com.nxtvibes.mobile',
      config: {
        googleMapsApiKey,
      },
    },
    android: {
      versionCode: 1,
      adaptiveIcon: {
        foregroundImage: './assets/applogo.png',
        backgroundColor: '#9d74f7',
      },
      package: 'com.nxtvibes.mobile',
      googleServicesFile: './google-services.json',
      edgeToEdge: true,
      config: {
        googleMaps: {
          apiKey: googleMapsApiKey,
        },
      },
      intentFilters: [
        {
          action: 'VIEW',
          autoVerify: true,
          data: [
            {
              scheme: 'https',
              host: 'nxtvibes.vercel.app',
              pathPrefix: '/trip',
            },
            {
              scheme: 'https',
              host: 'nxtvibes.vercel.app',
              pathPrefix: '/user',
            },
          ],
          category: ['BROWSABLE', 'DEFAULT'],
        },
      ],
      permissions: [
        'android.permission.INTERNET',
        'android.permission.ACCESS_NETWORK_STATE',
        'android.permission.ACCESS_WIFI_STATE',
        'android.permission.POST_NOTIFICATIONS',
        'android.permission.ACCESS_FINE_LOCATION',
        'android.permission.ACCESS_COARSE_LOCATION',
        'android.permission.CAMERA',
        'android.permission.READ_MEDIA_IMAGES',
        'android.permission.RECEIVE_BOOT_COMPLETED',
        'android.permission.VIBRATE',
        'android.permission.WAKE_LOCK',
        'android.permission.SCHEDULE_EXACT_ALARM',
      ],
      blockedPermissions: [
        'android.permission.READ_MEDIA_VIDEO',
        'android.permission.READ_MEDIA_AUDIO',
        'android.permission.RECORD_AUDIO',
      ],
    },
    plugins: [
      'expo-router',
      'expo-image',
      [
        'expo-notifications',
        {
          icon: './assets/notification-icon.png',
          color: '#9d74f7',
        },
      ],
      '@react-native-firebase/app',
      '@react-native-firebase/messaging',
      '@react-native-firebase/app-check',
      '@react-native-firebase/crashlytics',
      '@react-native-firebase/perf',
      [
        'expo-build-properties',
        {
          android: {
            usesCleartextTraffic: false,
            minSdkVersion: 24,
            compileSdkVersion: 36,
            targetSdkVersion: 35,
            enableProguardInReleaseBuilds: true,
            enableShrinkResourcesInReleaseBuilds: true,
            extraMavenRepos: [notifeeLibsPath],
          },
        },
      ],
      [
        'expo-location',
        {
          locationAlwaysAndWhenInUsePermission: 'Allow NxtVibes to use your location for sharing and maps.',
        },
      ],
      [
        'expo-image-picker',
        {
          photosPermission: 'Allow NxtVibes to access your photos for sharing.',
          cameraPermission: 'Allow NxtVibes to use your camera to take photos.',
        },
      ],
      [
        'expo-media-library',
        {
          photosPermission: 'Allow NxtVibes to save photos to your gallery.',
          savePhotosPermission: 'Allow NxtVibes to save photos to your gallery.',
          isAccessMediaLocationEnabled: true,
        },
      ],
      [
        '@morrowdigital/watermelondb-expo-plugin',
        {
          disableJsi: true,
        },
      ],
      '@react-native-community/datetimepicker',
      'expo-font',
      withCustomAndroidIcons,
    ],
  },
};
