// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvyhruuyaoarxyxzmixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2eWhydXV5YW9hcnh5eHptaXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MzQzODcsImV4cCI6MjA3NzMxMDM4N30.JTN6UeVw2sp6xkLvlxFGQ0yiwnWDZzSnWOp-HeDA-tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});